# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""OpenEnv server wrapper for the SurgeEnvV2 simulator."""

from typing import Optional

from openenv.core.env_server.interfaces import Environment
from openenv.core.env_server.types import State

try:
    from ..env import SurgeEnvV2
    from ..models import SurgeAction, SurgeObservation, SurgeState
except ImportError:
    from env import SurgeEnvV2
    from models import SurgeAction, SurgeObservation, SurgeState


class SurgeEnvironment(Environment):
    """OpenEnv-compatible environment backed by SurgeEnvV2 physics."""

    # Enable concurrent WebSocket sessions.
    # Set to True if your environment isolates state between instances.
    # When True, multiple WebSocket clients can connect simultaneously, each
    # getting their own environment instance (when using factory mode in app.py).
    SUPPORTS_CONCURRENT_SESSIONS: bool = True

    def __init__(self):
        super().__init__()
        self._sim = SurgeEnvV2()
        # Initialize simulator internals so state() is valid before first external reset.
        self._sim.reset_typed()
        self._state: SurgeState = self._sim.state()

    def reset(
        self,
        seed: Optional[int] = None,
        episode_id: Optional[str] = None,
        **kwargs,
    ) -> SurgeObservation:
        del episode_id  # Episode IDs are generated by the simulator.
        del kwargs

        resp = self._sim.reset_typed(seed=seed)
        self._state = self._sim.state()
        return resp.observation

    def step(
        self,
        action: SurgeAction,
        timeout_s: Optional[float] = None,
        **kwargs,
    ) -> SurgeObservation:  # type: ignore[override]
        del timeout_s
        del kwargs

        resp = self._sim.step_typed(action)
        self._state = self._sim.state()
        return resp.observation

    @property
    def state(self) -> State:
        """
        Get the current environment state.

        Returns:
            Current State with episode_id and step_count
        """
        return self._state
